// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AlignwithTower.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Climb.h"
#include "Commands/GotoWall.h"
#include "Commands/PickupDisk.h"
#include "Commands/PushDisk.h"
#include "Commands/ShootDisk.h"
#include "Commands/TeleoperatedCommand.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveJoystick = new Joystick(1);
	
	climbButton = new JoystickButton(driveJoystick, 2);
	climbButton->WhenPressed(new PickupDisk());
	shootDiskButton = new JoystickButton(driveJoystick, 1);
	shootDiskButton->WhenPressed(new ShootDisk());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Teleoperated Command", new TeleoperatedCommand());
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Go to Wall", new GotoWall());
	SmartDashboard::PutData("Shoot Disk", new ShootDisk());
	SmartDashboard::PutData("Pickup Disk", new PickupDisk());
	SmartDashboard::PutData("Climb", new Climb());
	SmartDashboard::PutData("Align with Tower", new AlignwithTower());
	SmartDashboard::PutData("Push Disk", new PushDisk());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriveJoystick() {
	return driveJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
