// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
//#define SHOOTER_P						5.0f
//#define SHOOTER_I						0.0f
//#define SHOOTER_D						0.0f
//#define SHOOTER_THRESHOLD				1.0f
/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Relay* diskPusher;
	GearTooth* shooterEncoder;
	SpeedController* shooterTalon1;
	SpeedController* shooterTalon2;
	DigitalInput* pusherStopSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Shooter();
	void InitDefaultCommand();
	//void SetWheelSpeed(float speed);
	//double ReturnPIDInput();
	//void UsePIDOutput(double);
	//void SetSpeed(double speed);
	//bool AtSetpoint();
	//void Stop();
};
#endif
